/**
 * AIEngine.js - Intelligence Hub for Westline Future.
 * All LLM calls route through a server-side proxy (Cloud Function or custom backend)
 * so API keys are never exposed in the browser bundle.
 */

const AI_PROXY_URL = import.meta.env.VITE_AI_PROXY_URL; // e.g. https://us-central1-<project>.cloudfunctions.net/generateProposal

export const AIEngine = {
  async generateProposal(project) {
    if (!AI_PROXY_URL) {
      if (import.meta.env.DEV) console.warn("[AI] VITE_AI_PROXY_URL not set — using fallback template.");
      return this.useFallbackTemplate(project);
    }

    try {
      const res = await fetch(AI_PROXY_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: project.title,
          type: project.type,
          glassType: project.specs?.glassType,
          dimensions: project.specs?.dimensions
        })
      });

      if (!res.ok) throw new Error(`Proxy HTTP ${res.status}`);
      const data = await res.json();
      return data.proposal || this.useFallbackTemplate(project);
    } catch (error) {
      if (import.meta.env.DEV) console.error("[AIEngine] Proposal generation failed:", error);
      return this.useFallbackTemplate(project);
    }
  },

  useFallbackTemplate(project) {
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `
# PROJECT PROPOSAL: ${project.title?.toUpperCase() || 'GLASSTECH PRECISION SYSTEM'}
**Date:** ${date}
**Reference ID:** LXF-${Math.floor(1000 + Math.random() * 9000)}
**Status:** Draft

---

## 1. Executive Summary
This proposal outlines the technical and aesthetic integration of premium ${project.type || 'Architectural'} solutions for the **${project.title || 'Client Development'}**. Westline Future will deploy industrial-grade precision engineering to ensure structural longevity and visual excellence.

## 2. Technical Scope of Fabrication
- **Structural Systems:** Custom aluminum framework with anodic coating.
- **Glass Integration:** ${project.specs?.glassType || 'Low-E Tempered Security Glass'} tailored to site-specific environmental loads.
- **Precision Detailing:** Micro-tolerance alignment using laser-guided structural audits.

## 3. Material Performance Benchmarks
| Feature | Benchmark | Compliance |
|---------|-----------|------------|
| Wind Load Resistance | Up to 2.5 kPa | ASTM E330 |
| Thermal Performance | U-Value < 1.8 W/m²K | ISO 15099 |
| Acoustic Dampening | STC 35-40 dB | ASTM E90 |

## 4. Estimated Timeline
- **Phase A (Procurement & Fabrication):** 21–25 Business Days
- **Phase B (On-site Integration):** 10–14 Business Days
- **Phase C (QA & Certification):** 3–5 Business Days

## 5. Structural Safety & Sustainability
All fabrications undergo multi-point SGS-certified inspection. We use sustainable aluminum sourcing and recycled content where possible, adhering to LEED-compliant standards.

---
*Generated by Westline Future Intelligence Hub.*
    `.trim();
  },

  calculateProjectRisk(project) {
    let risk = 'Low';
    if (project.complexity > 7 || project.budget > 50000) risk = 'Medium';
    if (project.structuralRequirements || project.customCurvature) risk = 'High';
    return risk;
  }
};
