import React, { useState, useEffect } from 'react';
import { Plus, Loader2, CheckCircle2, DollarSign, Zap, Edit2 } from 'lucide-react';
import { db } from '../../../lib/firebase';
import { collection, onSnapshot, query, orderBy, addDoc, serverTimestamp, doc, updateDoc, getDocs, where } from 'firebase/firestore';
import { SCHEDULE_CONFIGS } from './config.jsx';

// ─── Payment Schedule Card (admin) ───────────────────────────────────────────
export function PaymentScheduleCard({ project, notify, brand, invoices }) {
  const budget = Number(project.budget) || 0;
  const scheduleType = project.paymentSchedule || 'standard';
  const config = SCHEDULE_CONFIGS[scheduleType] || SCHEDULE_CONFIGS.standard;

  const [changing, setChanging] = useState(false);
  const [logging, setLogging] = useState(false);
  const [logForm, setLogForm] = useState({ amount: '', description: '', date: new Date().toISOString().slice(0, 10) });
  const [saving, setSaving] = useState(false);

  // ── Set Project Value ──────────────────────────────────────────────────────
  const [editingBudget, setEditingBudget] = useState(false);
  const [budgetInput, setBudgetInput] = useState('');
  const [settingBudget, setSettingBudget] = useState(false);

  useEffect(() => {
    if (editingBudget) setBudgetInput(budget > 0 ? String(budget) : '');
  }, [editingBudget, budget]);

  const handleSetBudget = async () => {
    const parsed = parseFloat(String(budgetInput).replace(/[^0-9.]/g, '')) || 0;
    if (!parsed || parsed <= 0) { notify?.('error', 'Enter a valid project value'); return; }
    if (!project?.id) return;
    setSettingBudget(true);
    try {
      // 1. Update project budget
      await updateDoc(doc(db, 'projects', project.id), { budget: String(parsed), projectTotal: String(parsed) });

      // 2. Check if milestone invoices already exist — if not, auto-generate them
      const schedule = SCHEDULE_CONFIGS[scheduleType] || SCHEDULE_CONFIGS.standard;
      if (schedule.milestones?.length && scheduleType !== 'custom') {
        const existingSnap = await getDocs(
          query(collection(db, 'invoices'), where('parentId', '==', project.id), where('type', '==', 'Milestone'))
        );
        const existingKeys = new Set(existingSnap.docs.map(d => d.data().milestoneKey).filter(Boolean));

        for (const m of schedule.milestones) {
          if (existingKeys.has(m.key)) {
            // Already exists — just update the amount to reflect new budget
            const existing = existingSnap.docs.find(d => d.data().milestoneKey === m.key);
            if (existing && !['Paid', 'paid'].includes(existing.data().status)) {
              await updateDoc(existing.ref, {
                amount: parseFloat((parsed * m.pct).toFixed(2)),
                title: m.label,
              });
            }
          } else {
            // Create new milestone invoice
            await addDoc(collection(db, 'invoices'), {
              parentId: project.id,
              projectId: project.id,
              clientId: project.clientId,
              title: m.label,
              amount: parseFloat((parsed * m.pct).toFixed(2)),
              type: 'Milestone',
              status: 'Pending',
              milestoneKey: m.key,
              date: new Date().toISOString().split('T')[0],
              due: null,
              autoGenerated: true,
              createdAt: serverTimestamp(),
            });
          }
        }
      }

      notify?.('success', `Project value set to GHS ${parsed.toLocaleString()}`);
      setEditingBudget(false);
    } catch (e) {
      notify?.('error', 'Failed to set project value');
      if (import.meta.env.DEV) console.error('[SetBudget]', e);
    }
    setSettingBudget(false);
  };

  // ── Live transactions ──────────────────────────────────────────────────────
  const [payments, setPayments] = useState([]);
  useEffect(() => {
    if (!db || !project?.id) return;
    const q = query(collection(db, 'projects', project.id, 'transactions'), orderBy('date', 'desc'));
    return onSnapshot(q, snap => setPayments(snap.docs.map(d => ({ id: d.id, ...d.data() }))), () => setPayments([]));
  }, [project?.id]);

  const totalPaid = payments.reduce((s, t) => s + (Number(t.amount) || 0), 0);
  const paidPct = budget > 0 ? Math.min(100, (totalPaid / budget) * 100) : 0;
  const remaining = Math.max(0, budget - totalPaid);

  const fmt = v => `GHS ${Number(v).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  const getMilestoneStatus = (m) => {
    // Check explicit invoice status first if we have the invoices array
    if (invoices && project?.id) {
      const milestoneInvoice = invoices.find(inv => (inv.projectId === project.id || inv.parentId === project.id) && inv.milestoneKey === m.key);
      if (milestoneInvoice) {
        if (milestoneInvoice.awaitingConfirmation === true || milestoneInvoice.status?.toLowerCase() === 'verification pending') {
          return 'verification pending';
        }
      }
    }

    if (budget <= 0) return 'upcoming';
    if (totalPaid >= budget * m.cumPct) return 'paid';
    if (totalPaid >= budget * (m.cumPct - m.pct)) return 'due';
    return 'upcoming';
  };

  const changeSchedule = async (type) => {
    if (!db || !project?.id) return;
    await updateDoc(doc(db, 'projects', project.id), { paymentSchedule: type });
    setChanging(false);
  };

  const logPayment = async () => {
    if (!logForm.amount || Number(logForm.amount) <= 0 || saving) return;
    setSaving(true);
    try {
      const amount = Number(logForm.amount);
      await addDoc(collection(db, 'projects', project.id, 'transactions'), {
        amount,
        description: logForm.description.trim() || 'Payment received',
        date: logForm.date,
        projectId: project.id,
        type: 'payment',
        createdAt: serverTimestamp(),
      });
      await updateDoc(doc(db, 'projects', project.id), { paidAmount: totalPaid + amount });
      setLogForm({ amount: '', description: '', date: new Date().toISOString().slice(0, 10) });
      setLogging(false);
    } catch (e) {
      if (import.meta.env.DEV) console.error('[logPayment]', e);
      notify?.('error', e.message || 'Failed to log payment');
    }
    setSaving(false);
  };

  const ac = brand?.color || 'var(--accent-secondary)';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

      {/* ── SET PROJECT VALUE CARD ── */}
      <div style={{
        padding: '20px 24px',
        background: budget > 0 ? '#fff' : `linear-gradient(135deg, ${ac}08, ${ac}14)`,
        borderRadius: 18,
        border: budget > 0 ? '1px solid var(--border-color)' : `2px solid ${ac}40`,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ width: 40, height: 40, borderRadius: 12, background: budget > 0 ? '#F0FDF4' : `${ac}15`, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <DollarSign size={18} color={budget > 0 ? '#16A34A' : ac} />
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 800, color: 'var(--accent-secondary)', marginBottom: 1 }}>Project Total Value</div>
              {budget > 0 ? (
                <div style={{ fontSize: 20, fontWeight: 900, color: 'var(--accent-secondary)' }}>{fmt(budget)}</div>
              ) : (
                <div style={{ fontSize: 12, color: 'var(--text-secondary)', fontWeight: 600 }}>Not set — enter after site assessment & rendering</div>
              )}
            </div>
          </div>

          {!editingBudget && (
            <button
              onClick={() => setEditingBudget(true)}
              style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '9px 18px', borderRadius: 11, background: budget > 0 ? 'var(--bg-secondary)' : ac, color: budget > 0 ? 'var(--text-secondary)' : '#fff', border: budget > 0 ? '1px solid var(--border-color)' : 'none', fontSize: 12, fontWeight: 800, cursor: 'pointer' }}
            >
              {budget > 0 ? <><Edit2 size={13} /> Edit Value</> : <><Zap size={13} /> Set Project Value</>}
            </button>
          )}
        </div>

        {editingBudget && (
          <div style={{ marginTop: 16, padding: '16px', background: 'var(--bg-secondary)', borderRadius: 14, display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--accent-secondary)' }}>
              {budget > 0 ? 'Update project total value' : 'Set project total value'}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
              {budget > 0
                ? 'Changing this will update existing unpaid milestone invoice amounts to match the new total.'
                : `This will auto-generate ${config.milestones?.length || 3} milestone invoices using the ${config.label} schedule (${config.sub}). Invoices will activate automatically when each project stage is reached.`}
            </div>
            <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <div style={{ position: 'relative', flex: 1 }}>
                <span style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', fontSize: 13, fontWeight: 700, color: 'var(--text-secondary)' }}>GHS</span>
                <input
                  type="number"
                  value={budgetInput}
                  onChange={e => setBudgetInput(e.target.value)}
                  placeholder="e.g. 85000"
                  style={{ width: '100%', padding: '10px 12px 10px 52px', borderRadius: 10, border: '1.5px solid var(--border-color)', fontSize: 14, fontWeight: 800, outline: 'none', boxSizing: 'border-box', fontFamily: 'inherit', color: 'var(--accent-secondary)' }}
                  onKeyDown={e => e.key === 'Enter' && handleSetBudget()}
                  autoFocus
                />
              </div>
              <button
                onClick={handleSetBudget}
                disabled={settingBudget || !budgetInput}
                style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '10px 20px', borderRadius: 10, background: ac, color: '#fff', border: 'none', fontSize: 13, fontWeight: 800, cursor: 'pointer', opacity: !budgetInput ? 0.5 : 1, whiteSpace: 'nowrap' }}
              >
                {settingBudget ? <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} /> : <Zap size={14} />}
                {settingBudget ? 'Saving...' : budget > 0 ? 'Update' : 'Set & Auto-Generate Invoices'}
              </button>
              <button
                onClick={() => setEditingBudget(false)}
                style={{ padding: '10px 14px', borderRadius: 10, background: '#fff', color: 'var(--text-secondary)', border: '1px solid var(--border-color)', fontSize: 12, fontWeight: 700, cursor: 'pointer' }}
              >
                Cancel
              </button>
            </div>
          </div>
        )}
      </div>

      {/* ── PAYMENT SCHEDULE CARD ── */}
      <div style={{ padding: '20px 24px', background: '#fff', borderRadius: 18, border: '1px solid var(--border-color)' }}>
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 }}>
          <div>
            <div style={{ fontSize: 13, fontWeight: 800, color: 'var(--accent-secondary)', marginBottom: 2 }}>Payment Schedule</div>
            <div style={{ fontSize: 11, color: 'var(--text-secondary)', fontWeight: 600 }}>{config.label}{config.sub ? ` · ${config.sub}` : ''}</div>
          </div>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
            {scheduleType === 'custom' && (
              <button
                onClick={() => setLogging(p => !p)}
                style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 10, background: 'var(--accent-secondary)', color: '#fff', border: 'none', fontSize: 12, fontWeight: 800, cursor: 'pointer' }}
              >
                <Plus size={13} /> Log Payment
              </button>
            )}
            <button
              onClick={() => setChanging(p => !p)}
              style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '7px 14px', borderRadius: 10, background: changing ? 'var(--accent-secondary)' : 'var(--bg-secondary)', color: changing ? '#fff' : 'var(--text-secondary)', border: '1px solid var(--border-color)', fontSize: 12, fontWeight: 700, cursor: 'pointer' }}
            >
              {changing ? 'Done' : 'Change Schedule'}
            </button>
          </div>
        </div>

        {/* Schedule picker */}
        {changing && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, marginBottom: 16, padding: '14px', background: 'var(--bg-secondary)', borderRadius: 14 }}>
            {Object.entries(SCHEDULE_CONFIGS).map(([key, cfg]) => (
              <button
                key={key}
                onClick={() => changeSchedule(key)}
                style={{
                  padding: '12px 10px', borderRadius: 12,
                  border: `2px solid ${scheduleType === key ? 'var(--accent-secondary)' : 'var(--border-color)'}`,
                  background: scheduleType === key ? 'var(--accent-secondary)' : '#fff',
                  cursor: 'pointer', textAlign: 'left', transition: 'all .15s',
                }}
              >
                <div style={{ fontSize: 12, fontWeight: 800, color: scheduleType === key ? '#fff' : 'var(--accent-secondary)', marginBottom: 3 }}>{cfg.label}</div>
                <div style={{ fontSize: 10, color: scheduleType === key ? 'rgba(255,255,255,.65)' : 'var(--text-secondary)', lineHeight: 1.4 }}>{cfg.sub}</div>
              </button>
            ))}
          </div>
        )}

        {/* Log Payment form (custom schedule) */}
        {logging && (
          <div style={{ marginBottom: 16, padding: '16px', background: 'var(--bg-secondary)', borderRadius: 14, display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ fontSize: 12, fontWeight: 800, color: 'var(--accent-secondary)' }}>Record a Payment</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
              <div>
                <label style={{ fontSize: 10, fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '.06em', display: 'block', marginBottom: 4 }}>Amount (GHS) *</label>
                <input
                  type="number"
                  value={logForm.amount}
                  onChange={e => setLogForm(p => ({ ...p, amount: e.target.value }))}
                  placeholder="e.g. 15000"
                  style={{ width: '100%', padding: '9px 12px', borderRadius: 10, border: '1.5px solid var(--border-color)', fontSize: 13, outline: 'none', boxSizing: 'border-box', fontFamily: 'inherit' }}
                />
              </div>
              <div>
                <label style={{ fontSize: 10, fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '.06em', display: 'block', marginBottom: 4 }}>Date</label>
                <input
                  type="date"
                  value={logForm.date}
                  onChange={e => setLogForm(p => ({ ...p, date: e.target.value }))}
                  style={{ width: '100%', padding: '9px 12px', borderRadius: 10, border: '1.5px solid var(--border-color)', fontSize: 13, outline: 'none', boxSizing: 'border-box', fontFamily: 'inherit' }}
                />
              </div>
            </div>
            <div>
              <label style={{ fontSize: 10, fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '.06em', display: 'block', marginBottom: 4 }}>Note</label>
              <input
                value={logForm.description}
                onChange={e => setLogForm(p => ({ ...p, description: e.target.value }))}
                placeholder="e.g. Second batch payment — wire transfer"
                style={{ width: '100%', padding: '9px 12px', borderRadius: 10, border: '1.5px solid var(--border-color)', fontSize: 13, outline: 'none', boxSizing: 'border-box', fontFamily: 'inherit' }}
              />
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button
                onClick={logPayment}
                disabled={saving || !logForm.amount}
                style={{ flex: 1, padding: '10px', borderRadius: 10, background: 'var(--accent-secondary)', color: '#fff', border: 'none', fontSize: 13, fontWeight: 800, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, opacity: !logForm.amount ? 0.5 : 1 }}
              >
                {saving ? <><Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} /> Saving...</> : 'Record Payment'}
              </button>
              <button onClick={() => setLogging(false)} style={{ padding: '10px 16px', borderRadius: 10, background: 'var(--bg-secondary)', color: 'var(--text-secondary)', border: '1px solid var(--border-color)', fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* No budget yet prompt */}
        {budget <= 0 && (
          <div style={{ padding: '18px', background: 'var(--bg-secondary)', borderRadius: 12, textAlign: 'center', marginBottom: 8 }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--accent-secondary)', marginBottom: 4 }}>Project value not yet set</div>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
              Set the total project value above after site assessment and rendering.<br />
              Milestone invoices will be auto-generated based on the <strong>{config.label}</strong> schedule.
            </div>
          </div>
        )}

        {/* Progress bar */}
        {budget > 0 && (
          <div style={{ marginBottom: config.milestones.length > 0 ? 14 : 0 }}>
            <div style={{ height: 7, background: 'var(--border-color)', borderRadius: 4, overflow: 'hidden', marginBottom: 6 }}>
              <div style={{ height: '100%', width: `${paidPct}%`, background: 'linear-gradient(90deg, #16A34A80, #16A34A)', borderRadius: 4, transition: 'width 1s ease' }} />
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11, color: 'var(--text-secondary)' }}>
              <span><strong style={{ color: '#16A34A' }}>{fmt(totalPaid)}</strong> paid · {paidPct.toFixed(1)}%</span>
              <span>{fmt(remaining)} remaining · {fmt(budget)} total</span>
            </div>
          </div>
        )}

        {/* Custom: recent payments mini-list */}
        {scheduleType === 'custom' && payments.length > 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginTop: 12 }}>
            {payments.slice(0, 5).map(p => (
              <div key={p.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '9px 12px', background: 'var(--bg-secondary)', borderRadius: 10 }}>
                <div>
                  <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--accent-secondary)' }}>{p.description || 'Payment'}</div>
                  <div style={{ fontSize: 10, color: 'var(--text-secondary)' }}>{p.date || '—'}</div>
                </div>
                <div style={{ fontSize: 13, fontWeight: 800, color: '#16A34A' }}>{fmt(p.amount)}</div>
              </div>
            ))}
            {payments.length > 5 && (
              <div style={{ fontSize: 11, color: 'var(--text-secondary)', textAlign: 'center', paddingTop: 4 }}>+{payments.length - 5} more payments</div>
            )}
          </div>
        )}

        {/* Milestone rows */}
        {config.milestones.length > 0 && budget > 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {config.milestones.map((m, idx) => {
              const status = getMilestoneStatus(m);
              const isPaid = status === 'paid';
              const isDue = status === 'due';
              const isPending = status === 'verification pending';
              return (
                <div key={m.key} style={{
                  display: 'flex', alignItems: 'center', gap: 12, padding: '12px 14px', borderRadius: 12,
                  background: isPending ? '#EFF6FF' : isDue ? '#F0FDF4' : '#FAFAF9',
                  border: `1.5px solid ${isPending ? '#DBEAFE' : isDue ? '#16A34A40' : isPaid ? '#16A34A20' : 'var(--border-color)'}`,
                }}>
                  <div style={{ width: 28, height: 28, borderRadius: 8, flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: isPaid ? '#16A34A' : isPending ? '#DBEAFE' : isDue ? '#F0FDF4' : 'var(--border-color)', border: isPending ? '2px solid #3B82F6' : isDue ? '2px solid #16A34A' : 'none' }}>
                    {isPaid ? <CheckCircle2 size={13} color="#fff" /> : <span style={{ fontSize: 10, fontWeight: 900, color: isPending ? '#3B82F6' : isDue ? '#16A34A' : 'var(--text-secondary)' }}>{idx + 1}</span>}
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--accent-secondary)' }}>{m.label}</div>
                    <div style={{ fontSize: 12, fontWeight: 800, color: isPaid ? '#16A34A' : isPending ? '#3B82F6' : isDue ? '#16A34A' : 'var(--text-secondary)' }}>{fmt(budget * m.pct)}</div>
                  </div>
                  <div>
                    {isPaid && <span style={{ fontSize: 10, fontWeight: 800, color: '#065F46', background: '#D1FAE5', padding: '3px 9px', borderRadius: 20 }}>Paid ✓</span>}
                    {isPending && <span style={{ fontSize: 10, fontWeight: 800, color: '#1E3A8A', background: '#DBEAFE', padding: '3px 9px', borderRadius: 20, whiteSpace: 'nowrap' }}>Verify Payment</span>}
                    {isDue && <span style={{ fontSize: 10, fontWeight: 800, color: '#92400E', background: '#FEF3C7', padding: '3px 9px', borderRadius: 20 }}>Due</span>}
                    {status === 'upcoming' && <span style={{ fontSize: 10, color: 'var(--text-secondary)', background: 'var(--border-color)', padding: '3px 9px', borderRadius: 20 }}>Upcoming</span>}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
